apiVersion: v2
name: app
version: 0.1.0
appVersion: "1.0.0"
description: Generic Java application Helm chart with Prometheus metrics support
keywords:
  - java
  - spring
  - prometheus
  - micrometer
type: application
